apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: nginx-service-ha
  namespace: dev
spec:
  ports:
  - name: loadbalancer-http
    nodePort: 30600  
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: LoadBalancer

