apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: dev
  labels:
    app: mysql
spec:
  capacity:
   storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 185.213.164.50
    path: "/storage/db/mysql" 