apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: dev
  labels:
    app: postgres
spec:
  capacity:
   storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 185.213.164.50
    path: "/storage/db/postgres" 
