apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
       app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata 
        ports:
        - containerPort: 5432
        
        envFrom:
         - configMapRef:
            name: postgres-configmap
        
        
        volumeMounts:
          - name: postgres-dev
            mountPath: /var/lib/postgresql/data/
      volumes:
         - name: postgres-dev
           persistentVolumeClaim:
             claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dev
  labels:
    app: postgres
spec:
#  type: ExternalName
#  externalName: mysql
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgres
