apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev
  name: postgres-configmap
data:
  POSTGRES_HOST: postgres
  POSTGRES_DATABASE: postgres_db
  POSTGRES_USER: postgres_usr
  POSTGRES_PASSWORD: postgres_pass
